openapi: 3.0.0
info:
  title: Calendar API
  description: Manipulates events and other calendar data.
  termsOfService: https://developers.google.com/terms/
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
  - analytics
  - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
  - format: google
    url: https://calendar-json.googleapis.com/$discovery/rest?version=v3
    version: v1
  x-providerName: googleapis.com
  x-serviceName: calendar
servers:
- url: https://www.googleapis.com/calendar/v3
tags:
- name: acl
- name: calendarList
- name: calendars
- name: channels
- name: colors
- name: events
- name: freebusy
paths:
  /calendars:
    post:
      tags:
      - calendars
      description: Creates a secondary calendar.
      operationId: create.calendar
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
  /calendars/{calendarId}:
    get:
      tags:
      - calendars
      description: Returns metadata for a calendar.
      operationId: calendar.calendars.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
    put:
      tags:
      - calendars
      description: Updates metadata for a calendar.
      operationId: calendar.calendars.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    delete:
      tags:
      - calendars
      description: Deletes a secondary calendar. Use calendars.clear for clearing
        all events on primary calendars.
      operationId: delete.calendar
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    patch:
      tags:
      - calendars
      description: Updates metadata for a calendar. This method supports patch semantics.
      operationId: calendar.calendars.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
  /calendars/{calendarId}/acl:
    get:
      tags:
      - acl
      description: Returns the rules in the access control list for the calendar.
      operationId: calendar.acl.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    post:
      tags:
      - acl
      description: Creates an access control rule.
      operationId: calendar.acl.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
  /calendars/{calendarId}/acl/{ruleId}:
    get:
      tags:
      - acl
      description: Returns an access control rule.
      operationId: calendar.acl.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
    put:
      tags:
      - acl
      description: Updates an access control rule.
      operationId: calendar.acl.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    delete:
      tags:
      - acl
      description: Deletes an access control rule.
      operationId: calendar.acl.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    patch:
      tags:
      - acl
      description: Updates an access control rule. This method supports patch semantics.
      operationId: calendar.acl.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
  /calendars/{calendarId}/clear:
    post:
      tags:
      - calendars
      description: Clears a primary calendar. This operation deletes all events associated
        with the primary calendar of an account.
      operationId: calendar.calendars.clear
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
  /calendars/{calendarId}/events:
    get:
      tags:
      - events
      description: Returns events on the specified calendar.
      operationId: calendar.events.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
    post:
      tags:
      - events
      description: Creates an event.
      operationId: calendar.events.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
  /calendars/{calendarId}/events/import:
    post:
      tags:
      - events
      description: Imports an event. This operation is used to add a private copy
        of an existing event to a calendar.
      operationId: calendar.events.import
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
  /calendars/{calendarId}/events/quickAdd:
    post:
      tags:
      - events
      description: Creates an event based on a simple text string.
      operationId: calendar.events.quickAdd
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
  /calendars/{calendarId}/events/{eventId}:
    get:
      tags:
      - events
      description: "Returns an event based on its Google Calendar ID. To retrieve\
        \ an event using its iCalendar ID, call the events.list method using the iCalUID\
        \ parameter."
      operationId: calendar.events.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
    put:
      tags:
      - events
      description: Updates an event.
      operationId: calendar.events.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
    delete:
      tags:
      - events
      description: Deletes an event.
      operationId: calendar.events.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
    patch:
      tags:
      - events
      description: Updates an event. This method supports patch semantics.
      operationId: calendar.events.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
  /calendars/{calendarId}/events/{eventId}/instances:
    get:
      tags:
      - events
      description: Returns instances of the specified recurring event.
      operationId: calendar.events.instances
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events.readonly
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
  /calendars/{calendarId}/events/{eventId}/move:
    post:
      tags:
      - events
      description: "Moves an event to another calendar, i.e. changes an event's organizer."
      operationId: calendar.events.move
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.events
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.events
  /colors:
    get:
      tags:
      - colors
      description: Returns the color definitions for calendars and events.
      operationId: calendar.colors.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
  /freeBusy:
    post:
      tags:
      - freebusy
      description: Returns free/busy information for a set of calendars.
      operationId: calendar.freebusy.query
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
  /users/me/calendarList:
    get:
      tags:
      - calendarList
      description: Returns the calendars on the user's calendar list.
      operationId: calendar.calendarList.list
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
    post:
      tags:
      - calendarList
      description: Inserts an existing calendar into the user's calendar list.
      operationId: calendar.calendarList.insert
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
  /users/me/calendarList/{calendarId}:
    get:
      tags:
      - calendarList
      description: Returns a calendar from the user's calendar list.
      operationId: calendar.calendarList.get
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
      - Oauth2:
        - https://www.googleapis.com/auth/calendar.readonly
        Oauth2c:
        - https://www.googleapis.com/auth/calendar.readonly
    put:
      tags:
      - calendarList
      description: Updates an existing calendar on the user's calendar list.
      operationId: calendar.calendarList.update
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    delete:
      tags:
      - calendarList
      description: Removes a calendar from the user's calendar list.
      operationId: calendar.calendarList.delete
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
    patch:
      tags:
      - calendarList
      description: Updates an existing calendar on the user's calendar list. This
        method supports patch semantics.
      operationId: calendar.calendarList.patch
      security:
      - Oauth2:
        - https://www.googleapis.com/auth/calendar
        Oauth2c:
        - https://www.googleapis.com/auth/calendar
components:
  securitySchemes:
    Oauth2:
      type: oauth2
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/calendar: "See, edit, share, and permanently\
              \ delete all the calendars you can access using Google Calendar"
            https://www.googleapis.com/auth/calendar.events: View and edit events
              on all your calendars
            https://www.googleapis.com/auth/calendar.events.readonly: View events
              on all your calendars
            https://www.googleapis.com/auth/calendar.readonly: See and download any
              calendar you can access using your Google Calendar
    Oauth2c:
      type: oauth2
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          tokenUrl: https://accounts.google.com/o/oauth2/token
          scopes:
            https://www.googleapis.com/auth/calendar: "See, edit, share, and permanently\
              \ delete all the calendars you can access using Google Calendar"
            https://www.googleapis.com/auth/calendar.events: View and edit events
              on all your calendars
            https://www.googleapis.com/auth/calendar.events.readonly: View events
              on all your calendars
            https://www.googleapis.com/auth/calendar.readonly: See and download any
              calendar you can access using your Google Calendar
